export interface Product {
  id: number
  name: string
  category: string
  price: string
  image: string
  description: string
}

export const products: Product[] = [
  {
    id: 1,
    name: "Anchor Nut",
    category: "Hardware",
    price: "",
    image: "/anchor-nut.png",
    description: "High quality anchor nuts for secure fastening applications",
  },
  {
    id: 2,
    name: "Tay Rod",
    category: "Construction Materials",
    price: "",
    image: "/tay-rod.png",
    description: "Durable tay rods for construction and reinforcement work",
  },
  {
    id: 3,
    name: "Wing Nut",
    category: "Hardware",
    price: "",
    image: "/wing-nut-img.png",
    description: "Easy-to-use wing nuts for quick assembly and disassembly",
  },
  {
    id: 4,
    name: "M.S Wire",
    category: "Wire Materials",
    price: "",
    image: "/ms-wire-img.png",
    description: "Mild steel wire for various construction applications",
  },
  {
    id: 5,
    name: "Nitrile Coated Safety Gloves",
    category: "Safety Materials",
    price: "",
    image: "/nitrile-coated-safety-gloves-img.png",
    description: "Chemical resistant safety gloves with nitrile coating",
  },
  {
    id: 6,
    name: "MS Construction Wire Nails",
    category: "Nails Materials",
    price: "",
    image: "/ms-construction-wire-nails-img.png",
    description: "Mild steel construction wire nails for heavy-duty applications",
  },
  {
    id: 7,
    name: "Mild Steel Wire Nail",
    category: "Nails Materials",
    price: "",
    image: "/mild-steel-wire-nails-img.png",
    description: "High quality mild steel wire nails for construction work",
  },
  {
    id: 8,
    name: "Sledgehammer Heads",
    category: "Tools",
    price: "",
    image: "/sledgehammer-heads-img.png",
    description: "Heavy duty sledgehammer heads for demolition work",
  },
  {
    id: 9,
    name: "Forged Swivel Clamps (40 mm x 40 mm)",
    category: "Hardware",
    price: "",
    image: "/Forged-swivel-clamp-img.png",
    description: "Forged swivel clamps for secure connections and fittings",
  },
  {
    id: 10,
    name: "Industrial Safety Goggles",
    category: "Safety Materials",
    price: "",
    image: "/industrial-safety-gloves-img.png",
    description: "Protective safety goggles for industrial work environments",
  },
  {
    id: 11,
    name: "Full Body Safety Belt",
    category: "Safety Materials",
    price: "",
    image: "/safety-belt-img.png",
    description: "Complete body safety belt for fall protection and safety",
  },
  {
    id: 12,
    name: "Safety Jacket",
    category: "Safety Materials",
    price: "",
    image: "/safety-jacket-img.png",
    description: "High visibility safety jacket for construction workers",
  },
  {
    id: 13,
    name: "Industrial Safety Shoes",
    category: "Safety Materials",
    price: "",
    image: "/industrial-safety-shoes-img'.png",
    description: "Protective industrial safety shoes for workplace safety",
  },
  {
    id: 14,
    name: "Industrial Dotted Hand Gloves",
    category: "Safety Materials",
    price: "",
    image: "/dotted-gloves-img.png",
    description: "Industrial dotted hand gloves for enhanced grip and protection",
  },
  {
    id: 15,
    name: "PVC Hand Gloves",
    category: "Safety Materials",
    price: "",
    image: "/pvc-gloves-img.png",
    description: "PVC coated hand gloves for chemical and liquid protection",
  },
  {
    id: 16,
    name: "Red Hand Gloves",
    category: "Safety Materials",
    price: "",
    image: "/red-gloves-img.png",
    description: "High visibility red hand gloves for safety and identification",
  },
  {
    id: 17,
    name: "Cotton Hand Gloves",
    category: "Safety Materials",
    price: "",
    image: "/cotton-gloves-img.png",
    description: "Comfortable cotton hand gloves for general work protection",
  },
  {
    id: 18,
    name: "Industries Hand Gloves",
    category: "Safety Materials",
    price: "",
    image: "/industrial-hand-gloves-img.png",
    description: "Professional industrial hand gloves for heavy-duty work",
  },
  {
    id: 19,
    name: "Cement Nails",
    category: "Nails Materials",
    price: "",
    image: "/cement-nails-img.png",
    description: "Specialized cement nails for concrete and masonry work",
  },
  {
    id: 20,
    name: "Concertina Coil Wire",
    category: "Wire Materials",
    price: "",
    image: "/concertina-coil-wire-img.png",
    description: "Security concertina coil wire for perimeter protection",
  },
  {
    id: 21,
    name: "G.I Barbed Wire",
    category: "Wire Materials",
    price: "",
    image: "/GI-barbed-wire-img.png",
    description: "Galvanized iron barbed wire for fencing and security",
  },
  {
    id: 22,
    name: "Barricade Tape",
    category: "Safety Materials",
    price: "",
    image: "/barricade-tape-img.png",
    description: "High visibility barricade tape for safety and warning purposes",
  },
  {
    id: 23,
    name: "M.S Binding Wire ",
    category: "Wire Materials",
    price: "",
    image: "/ms-banding-wire-u-img.png",
    description: "Mild steel banding wire for packaging and bundling applications",
  },
  {
    id: 24,
    name: "Galvanize Iron Wire",
    category: "Wire Materials",
    price: "",
    image: "/galvanize-iron-wire-img.png",
    description: "Galvanized iron wire for corrosion resistance and durability",
  },
  {
    id: 25,
    name: "Galista Safety Shoes",
    category: "Safety Materials",
    price: "",
    image: "/galista-safety-shoes.png",
    description: "Premium Galista safety shoes for industrial protection",
  },
  {
    id: 26,
    name: "Elecant Safety Shoes",
    category: "Safety Materials",
    price: "",
    image: "/elecant-safety-shoes.png",
    description: "Elegant safety shoes combining style with workplace protection",
  },
  {
    id: 27,
    name: "PVC Farming Wire",
    category: "Wire Materials",
    price: "",
    image: "/pvc-farming-wire.png",
    description: "PVC coated farming wire for agricultural applications",
  },
  {
    id: 28,
    name: "PVC Coated Cloth Wire",
    category: "Wire Materials",
    price: "",
    image: "/pvc-coated-cloth-wire-img.png",
    description: "PVC coated cloth wire for electrical and construction applications",
  },
  {
    id: 29,
    name: "Nails",
    category: "Nails Materials",
    price: "",
    image: "/nails-img.png",
    description: "High quality construction nails for various building applications",
  },
  {
    id: 30,
    name: "Quarter Pin",
    category: "Hardware",
    price: "",
    image: "/quarter-pin-img.png",
    description: "Precision quarter pins for mechanical and construction applications",
  },
  {
    id: 31,
    name: "L.J. Pipe Hook",
    category: "Hardware",
    price: "",
    image: "/L-J-pipe-hook-img.png",
    description: "L.J. pipe hooks for secure pipe mounting and support systems",
  },
  {
    id: 32,
    name: "PVC Cap",
    category: "Hardware",
    price: "",
    image: "/pvc-cap-img.png",
    description: "PVC caps for pipe protection and sealing applications",
  },
  {
    id: 33,
    name: "Nut",
    category: "Hardware",
    price: "",
    image: "/nut-img.png",
    description: "Standard nuts for fastening and assembly applications",
  },
  {
    id: 34,
    name: "Ribit",
    category: "Hardware",
    price: "",
    image: "/ribit-img.png",
    description: "Ribit fasteners for secure connections and structural applications",
  },
  {
    id: 35,
    name: "L Hook",
    category: "Hardware",
    price: "",
    image: "/L-hook-img.png",
    description: "L-shaped hooks for hanging and mounting applications",
  },
  {
    id: 36,
    name: "C Hook",
    category: "Hardware",
    price: "",
    image: "/C-hook-img.png",
    description: "C-shaped hooks for versatile hanging and support systems",
  },
  {
    id: 37,
    name: "Patti Hook",
    category: "Hardware",
    price: "",
    image: "/patti-hook-img.png",
    description: "Patti hooks for specialized mounting and hanging applications",
  },
  {
    id: 38,
    name: "Pipe Hook",
    category: "Hardware",
    price: "",
    image: "/pipe-hook-img.png",
    description: "Pipe hooks designed for secure pipe mounting and support",
  },
  {
    id: 39,
    name: "Cycle Hook",
    category: "Hardware",
    price: "",
    image: "/cycle-hook-img.png",
    description: "Cycle hooks for bicycle storage and mounting solutions",
  },
  {
    id: 40,
    name: "S Hook",
    category: "Hardware",
    price: "",
    image: "/S-hook-img.png",
    description: "S-shaped hooks for versatile hanging and connection applications",
  },
  {
    id: 41,
    name: "Box Hook",
    category: "Hardware",
    price: "",
    image: "/box-hook-img.png",
    description: "Box hooks for secure box and container mounting",
  },
  {
    id: 42,
    name: "Gadar Hook",
    category: "Hardware",
    price: "",
    image: "/gadar-hook-img.png",
    description: "Gadar hooks for heavy-duty mounting and support applications",
  },
  {
    id: 43,
    name: "Dag",
    category: "Hardware",
    price: "",
    image: "/dag-img.png",
    description: "Dag fasteners for secure connections and structural applications",
  },
  {
    id: 44,
    name: "Hole Pass",
    category: "Hardware",
    price: "",
    image: "/hole-paas-img.png",
    description: "Hole pass components for cable and wire management systems",
  },
  {
    id: 45,
    name: "Colom Patti",
    category: "Hardware",
    price: "",
    image: "/colom-patti-img.png",
    description: "Colom patti for structural support and reinforcement applications",
  },
  {
    id: 46,
    name: "Pully",
    category: "Hardware",
    price: "",
    image: "/pully-img.png",
    description: "Standard pulleys for lifting and mechanical applications",
  },
  {
    id: 47,
    name: "Wheel Pully",
    category: "Hardware",
    price: "",
    image: "/wheel-pully-img.png",
    description: "Wheel pulleys for enhanced mechanical advantage and lifting",
  },
  {
    id: 48,
    name: "Buckle",
    category: "Hardware",
    price: "",
    image: "/buckle-img.png",
    description: "Buckles for fastening and securing applications",
  },
  {
    id: 49,
    name: "China Double Pully",
    category: "Hardware",
    price: "",
    image: "/china-double-pully-img.png",
    description: "China double pulleys for heavy-duty lifting and mechanical systems",
  },
  {
    id: 50,
    name: "Brass Pully",
    category: "Hardware",
    price: "",
    image: "/brass-pully-img.png",
    description: "Brass pulleys for corrosion-resistant mechanical applications",
  },
  {
    id: 51,
    name: "Brass Double Pully",
    category: "Hardware",
    price: "",
    image: "/brass-double-pully-img.png",
    description: "Brass double pulleys for heavy-duty corrosion-resistant applications",
  },
  {
    id: 52,
    name: "Small Nut",
    category: "Hardware",
    price: "",
    image: "/small-nut-img.png",
    description: "Small nuts for precision fastening and assembly applications",
  },
  {
    id: 53,
    name: "Rigid Coupling",
    category: "Ductile Iron Grooved",
    price: "",
    image: "/rigid-coupling-img.png",
    description: "Rigid coupling for secure pipe connections",
  },
  {
    id: 54,
    name: "Flexible Coupling",
    category: "Ductile Iron Grooved",
    price: "",
    image: "/flexible-coupling-img.png",
    description: "Flexible coupling for pipe systems requiring flexibility",
  },
  {
    id: 55,
    name: "Mechanical Tee Grooved outlet",
    category: "Ductile Iron Grooved",
    price: "",
    image: "/mechanica-tee-grooved-outlet-img.png",
    description: "Mechanical tee with grooved outlet for pipe branching",
  },
  {
    id: 56,
    name: "Mechanical Tee Threaded outlet",
    category: "Ductile Iron Grooved",
    price: "",
    image: "/mechanical-tee-threaded-outlet-img.png",
    description: "Mechanical tee with threaded outlet for pipe connections",
  },
  {
    id: 57,
    name: "U-Bolt Mechanical Tee",
    category: "Ductile Iron Grooved",
    price: "",
    image: "/u-bolt-mechanical-tee-img.png",
    description: "U-bolt mechanical tee for secure pipe connections",
  },
  {
    id: 58,
    name: "Grooved flange",
    category: "Ductile Iron Grooved",
    price: "",
    image: "/grooved-flange-img.png",
    description: "Grooved flange for pipe flanging applications",
  },
  {
    id: 59,
    name: "90°Elbow",
    category: "Ductile Iron Grooved",
    price: "",
    image: "/90-degree-elbow-img.png",
    description: "90 degree elbow for pipe direction changes",
  },
  {
    id: 60,
    name: "45°Elbow",
    category: "Ductile Iron Grooved",
    price: "",
    image: "/45-degree-elbow-img.png",
    description: "45 degree elbow for pipe direction changes",
  },
  {
    id: 61,
    name: "22.5°Elbow",
    category: "Ductile Iron Grooved",
    price: "",
    image: "/22.5-degree-elbow-img.png",
    description: "22.5 degree elbow for gradual pipe direction changes",
  },
  {
    id: 62,
    name: "11.25°Elbow",
    category: "Ductile Iron Grooved",
    price: "",
    image: "/11.25-degree-elbow-img.png",
    description: "11.25 degree elbow for subtle pipe direction changes",
  },
  {
    id: 63,
    name: "Tee",
    category: "Ductile Iron Grooved",
    price: "",
    image: "/tee-img.png",
    description: "Tee fitting for pipe branching applications",
  },
  {
    id: 64,
    name: "Grooved Reducing Tee",
    category: "Ductile Iron Grooved",
    price: "",
    image: "/grooved-reducing-tee-img.png",
    description: "Grooved reducing tee for pipe size reduction and branching",
  },
  {
    id: 65,
    name: "Threaded Reducing Tee",
    category: "Ductile Iron Grooved",
    price: "",
    image: "/threaded-reducing-tee-img.png",
    description: "Threaded reducing tee for pipe size reduction with threaded connections",
  },
  {
    id: 66,
    name: "Cross",
    category: "Ductile Iron Grooved",
    price: "",
    image: "/cross-img.png",
    description: "Cross fitting for four-way pipe connections",
  },
  {
    id: 67,
    name: "Grooved Reducing Cross",
    category: "Ductile Iron Grooved",
    price: "",
    image: "/grooved-reducing-cross-img.png",
    description: "Grooved reducing cross for pipe size reduction in cross configurations",
  },
  {
    id: 68,
    name: "Threaded Reducing Cross",
    category: "Ductile Iron Grooved",
    price: "",
    image: "/threaded-reducing-cross-img.png",
    description: "Threaded reducing cross for pipe size reduction with threaded connections",
  },
  {
    id: 69,
    name: "Cap",
    category: "Ductile Iron Grooved",
    price: "",
    image: "/cap-img.png",
    description: "Cap fitting for pipe end closures",
  },
  {
    id: 70,
    name: "Grooved Concentric Reducer",
    category: "Ductile Iron Grooved",
    price: "",
    image: "/grooved-concentric-reducer-img.png",
    description: "Grooved concentric reducer for centered pipe size reduction",
  },
  {
    id: 71,
    name: "Threaded Concentric Reducer",
    category: "Ductile Iron Grooved",
    price: "",
    image: "/threaded-concentric-reducer-img.png",
    description: "Threaded concentric reducer for centered pipe size reduction with threaded connections",
  },
  {
    id: 72,
    name: "Grooved Eccentric Reducer",
    category: "Ductile Iron Grooved",
    price: "",
    image: "/grooved-eccentric-reducer-img.png",
    description: "Grooved eccentric reducer for offset pipe size reduction",
  },
  {
    id: 73,
    name: "Adaptor Flange",
    category: "Ductile Iron Grooved",
    price: "",
    image: "/adaptor-flange-img.png",
    description: "Adaptor flange for connecting grooved pipes to flanged systems",
  },
  {
    id: 74,
    name: "C.I. SLUICE VALVE",
    category: "Catalogue Valve",
    price: "",
    image: "/c.i-sluice-valve-img.png",
    description: "Cast iron sluice valve for water control applications",
  },
  {
    id: 75,
    name: "RESILIENT SEATED DUCTILE IRON SLUICE VALVE",
    category: "Catalogue Valve",
    price: "",
    image: "/resilent-seated-ductile-iron-sluice-valve-img.png",
    description: "Resilient seated ductile iron sluice valve for reliable water control",
  },
  {
    id: 76,
    name: "CAST IRON NON-RETURN VALVE SWING TYPE (Reflex Value)",
    category: "Catalogue Valve",
    price: "",
    image: "/cast-iron-non-return-valve-swing-type-img.png",
    description: "Cast iron non-return swing type valve for preventing backflow",
  },
  {
    id: 77,
    name: "BUTTERFLY VALVE",
    category: "Catalogue Valve",
    price: "",
    image: "/butterfly-valve-img.png",
    description: "Butterfly valve for efficient flow control in pipe systems",
  },
  {
    id: 78,
    name: "CAST IRON DUAL PLATE CHECK VALVE",
    category: "Catalogue Valve",
    price: "",
    image: "/cast-iron-dual-plate-check-valve-iron-img.png",
    description: "Cast iron dual plate check valve for backflow prevention",
  },
  {
    id: 79,
    name: "WAFER TYPE CHECK VALVE",
    category: "Catalogue Valve",
    price: "",
    image: "/wafer-type-check-walve-img.png",
    description: "Wafer type check valve for space-saving backflow prevention",
  },
  {
    id: 80,
    name: "FORGED BRASS BALL VALVES",
    category: "Catalogue Valve",
    price: "",
    image: "/forged-brass-ball-valves-img.png",
    description: "Forged brass ball valves for reliable shut-off control",
  },
  {
    id: 81,
    name: "PRESSSURE REDUCINNG VALVES",
    category: "Catalogue Valve",
    price: "",
    image: "/pressure-reducing-valves-img.png",
    description: "Pressure reducing valves for maintaining optimal system pressure",
  },
  {
    id: 82,
    name: "FORGED BRASS AIR RЕLEASE VALVE",
    category: "Catalogue Valve",
    price: "",
    image: "/forged-brass-air-release-valve-img.png",
    description: "Forged brass air release valve for removing trapped air from systems",
  },
  {
    id: 83,
    name: "MULTI-UTILITY CHECK VALVE",
    category: "Catalogue Valve",
    price: "",
    image: "/multi-utility-check-valve-img.png",
    description: "Multi-utility check valve for versatile backflow prevention",
  },
  {
    id: 84,
    name: "CHECK VALVE (SWING TYPE)",
    category: "Catalogue Valve",
    price: "",
    image: "/check-valve-img.png",
    description: "Swing type check valve for preventing reverse flow",
  },
  {
    id: 85,
    name: "CAST IRON 'Y' TYPE STAINER (Flanged)",
    category: "Catalogue Valve",
    price: "",
    image: "/cast-iron-y-type-strainer-flanged-img.png",
    description: "Cast iron Y-type strainer with flanged connection for debris filtration",
  },
  {
    id: 86,
    name: "CAST IRON 'Y' TYPE STRAINER (Screwed)",
    category: "Catalogue Valve",
    price: "",
    image: "/cast-iron-y-type-strainer-screwed-img.png",
    description: "Cast iron Y-type strainer with screwed connection for debris filtration",
  },
  {
    id: 87,
    name: "C.I. BALL VALVE (Screwed)",
    category: "Catalogue Valve",
    price: "",
    image: "/c.i-ball-valve-screwed-img.png",
    description: "Cast iron ball valve with screwed connection for flow control",
  },
  {
    id: 88,
    name: "C.I. BALL VALVE FLANGED",
    category: "Catalogue Valve",
    price: "",
    image: "/c.i-ball-valve-flanged-img.png",
    description: "Cast iron ball valve with flanged connection for flow control",
  },
  {
    id: 89,
    name: "C.I. KINETIC AIR VALVE (FLANGED)",
    category: "Catalogue Valve",
    price: "",
    image: "/c.i-kinetic-air-valve-flanged-img.png",
    description: "Cast iron kinetic air valve with flanged connection for air management",
  },
  {
    id: 90,
    name: "CAST IRON DOUBLE AIR VALVE",
    category: "Catalogue Valve",
    price: "",
    image: "/cast-iron-double-air-valve-img.png",
    description: "Cast iron double air valve for comprehensive air release and vacuum breaking",
  },
  {
    id: 91,
    name: "CAST IRON SINGLE AIR VALVE (Screwed)",
    category: "Catalogue Valve",
    price: "",
    image: "/cast-iron-single-air-valve-screwed-img.png",
    description: "Cast iron single air valve with screwed connection for air release",
  },
  {
    id: 92,
    name: "CAST IRON GLOBE STEAM STOP VALVE (Flanged)",
    category: "Catalogue Valve",
    price: "",
    image: "/cast-iron-global-steam-stop-valve-flanged-img.png",
    description: "Cast iron globe steam stop valve with flanged connection for steam control",
  },
  {
    id: 93,
    name: "CAST IRON HORIZONTAL LIFT CHECK VALVE (Flanged)",
    category: "Catalogue Valve",
    price: "",
    image: "/cast-iron-horizontal-lift-check-valve-flanged-img.png",
    description: "Cast iron horizontal lift check valve with flanged connection for backflow prevention",
  },
  {
    id: 94,
    name: "GUN METAL GATE VALVE (Screwed)",
    category: "Catalogue Valve",
    price: "",
    image: "/gun-metal-gate-valve-screwed-img.png",
    description: "Gun metal gate valve with screwed connection for isolation control",
  },
  {
    id: 95,
    name: "GUN METAL WHEEL VALVE (Screwed)",
    category: "Catalogue Valve",
    price: "",
    image: "/gun-metal-wheel-valve-screwed-img.png",
    description: "Gun metal wheel valve with screwed connection for manual flow control",
  },
  {
    id: 96,
    name: "GUN METAL HORIZONTAL CHECK VALVE (Screwed)",
    category: "Catalogue Valve",
    price: "",
    image: "/gun-metal-horizontal-check-valve-screwed-img.png",
    description: "Gun metal horizontal check valve with screwed connection for backflow prevention",
  },
  {
    id: 97,
    name: "GUN METAL VERTICAL CHECK VALVE (Screwed)",
    category: "Catalogue Valve",
    price: "",
    image: "/gun-metal-vertical-check-valve-screwed-img.png",
    description: "Gun metal vertical check valve with screwed connection for backflow prevention",
  },
  {
    id: 98,
    name: "Lead Free Ball Valve",
    category: "Plumbing Catalogue",
    price: "",
    image: "/plumbing-1.png",
    description: "Lead-free ball valve for safe potable water systems",
  },
  {
    id: 99,
    name: "Forged Brass Bib Cock",
    category: "Plumbing Catalogue",
    price: "",
    image: "/plumbing-2.png",
    description: "Durable forged brass bib cock for reliable water control",
  },
  {
    id: 100,
    name: "Brass & PP Y-Type  Strainer",
    category: "Plumbing Catalogue",
    price: "",
    image: "/plumbing-3.png",
    description: "Brass and PP Y-type strainer for debris filtration in pipelines",
  },
  {
    id: 101,
    name: "Y-Type Strainer",
    category: "Plumbing Catalogue",
    price: "",
    image: "/plumbing-4.png",
    description: "Standard Y-type strainer for protecting valves and equipment",
  },
  {
    id: 102,
    name: "T-Type Strainer",
    category: "Plumbing Catalogue",
    price: "",
    image: "/plumbing-5.png",
    description: "T-type strainer for efficient filtration in plumbing systems",
  },
  {
    id: 103,
    name: "Brass Check Valve",
    category: "Plumbing Catalogue",
    price: "",
    image: "/plumbing-6.png",
    description: "Brass check valve for preventing reverse flow",
  },
  {
    id: 104,
    name: "Dual Plate Check Valve",
    category: "Plumbing Catalogue",
    price: "",
    image: "/plumbing-7.png",
    description: "Compact dual plate check valve for backflow prevention",
  },
  {
    id: 105,
    name: "Reflux Valve",
    category: "Plumbing Catalogue",
    price: "",
    image: "/plumbing-8.png",
    description: "Reflux valve designed to stop reverse fluid movement",
  },
  {
    id: 106,
    name: "Silence Check Valve",
    category: "Plumbing Catalogue",
    price: "",
    image: "/plumbing-9.png",
    description: "Silent check valve minimizing noise in plumbing systems",
  },
  {
    id: 107,
    name: "Sluice Valve",
    category: "Plumbing Catalogue",
    price: "",
    image: "/plumbing-10.png",
    description: "Sluice valve for isolation control in pipelines",
  },
  {
    id: 108,
    name: "Air Release Valve",
    category: "Plumbing Catalogue",
    price: "",
    image: "/plumbing-11.png",
    description: "Air release valve for removing trapped air from water lines",
  },
  {
    id: 109,
    name: "Foot Valve",
    category: "Plumbing Catalogue",
    price: "",
    image: "/plumbing-12.png",
    description: "Foot valve for maintaining pump priming",
  },
  {
    id: 110,
    name: "Ball Type NRV & Foot Valves",
    category: "Plumbing Catalogue",
    price: "",
    image: "/plumbing-13.png",
    description: "Ball type non-return and foot valves for reliable flow control",
  },
  {
    id: 111,
    name: "Water Hammer Arrestors",
    category: "Plumbing Catalogue",
    price: "",
    image: "/plumbing-14.png",
    description: "Water hammer arrestors to mitigate pressure surges",
  },
  {
    id: 112,
    name: "Pressure Reducing Valves",
    category: "Plumbing Catalogue",
    price: "",
    image: "/plumbing-15.png",
    description: "Pressure reducing valves for consistent downstream pressure",
  },
  {
    id: 113,
    name: "Automatic Control Valve",
    category: "Plumbing Catalogue",
    price: "",
    image: "/plumbing-16.png",
    description: "Automatic control valve for dynamic flow regulation",
  },
  {
    id: 114,
    name: "Single jet  Water Meters",
    category: "Plumbing Catalogue",
    price: "",
    image: "/plumbing-17.png",
    description: "Single jet water meters for accurate residential metering",
  },
  {
    id: 115,
    name: "Multi jet  Water Meters",
    category: "Plumbing Catalogue",
    price: "",
    image: "/plumbing-18.png",
    description: "Multi jet water meters for dependable consumption tracking",
  },
  {
    id: 116,
    name: "Multi jet Vertical Type Water Meters",
    category: "Plumbing Catalogue",
    price: "",
    image: "/plumbing-19.png",
    description: "Vertical multi jet water meters for compact installations",
  },
  {
    id: 117,
    name: "Volumetric Water Meters",
    category: "Plumbing Catalogue",
    price: "",
    image: "/plumbing-20.png",
    description: "Volumetric water meters for precise low-flow measurement",
  },
  {
    id: 118,
    name: "Irrigation Water Meters",
    category: "Plumbing Catalogue",
    price: "",
    image: "/plumbing-21.png",
    description: "Water meters designed for agricultural irrigation systems",
  },
  {
    id: 119,
    name: "Woltmann Type Water Meters",
    category: "Plumbing Catalogue",
    price: "",
    image: "/plumbing-22.png",
    description: "Woltmann type meters for high flow industrial applications",
  },
  {
    id: 120,
    name: "Electromagnetic Flow Meters",
    category: "Plumbing Catalogue",
    price: "",
    image: "/plumbing-23.png",
    description: "Electromagnetic flow meters for non-intrusive measurements",
  },
  {
    id: 121,
    name: "Ex-Stem Ball Valve with Strainer",
    category: "Plumbing Catalogue",
    price: "",
    image: "/plumbing-24.png",
    description: "Extended stem ball valve integrated with strainer",
  },
  {
    id: 122,
    name: "Balancing Valve Screwed",
    category: "Plumbing Catalogue",
    price: "",
    image: "/plumbing-25.png",
    description: "Screwed balancing valve for hydronic system tuning",
  },
  {
    id: 123,
    name: "Balancing Valve Flanged",
    category: "Plumbing Catalogue",
    price: "",
    image: "/plumbing-26.png",
    description: "Flanged balancing valve for large pipe networks",
  },
  {
    id: 124,
    name: "Pr. Independent Balancing & Control Valve",
    category: "Plumbing Catalogue",
    price: "",
    image: "/plumbing-27.png",
    description: "Pressure independent balancing and control valve",
  },
  {
    id: 125,
    name: "Dynamic Flow Automatic Balancing Valve",
    category: "Plumbing Catalogue",
    price: "",
    image: "/plumbing-28.png",
    description: "Dynamic flow automatic balancing valve for HVAC systems",
  },
  {
    id: 126,
    name: "Electrical 2/3/4- Way Control Valve Screwed",
    category: "Plumbing Catalogue",
    price: "",
    image: "/plumbing-29.png",
    description: "Electrical 2/3/4-way control valve with screwed connections",
  },
  {
    id: 127,
    name: "FCU Valve Package Unit",
    category: "Plumbing Catalogue",
    price: "",
    image: "/plumbing-30.png",
    description: "Fan coil unit valve package for simplified installations",
  },
  {
    id: 128,
    name: "UL & FM Approved Swing Check Valve",
    category: "Plumbing Catalogue",
    price: "",
    image: "/plumbing-31.png",
    description: "UL and FM approved swing check valve for fire protection",
  },
  {
    id: 129,
    name: "UL & FM OS&Y Type Gate Valve Flanged End",
    category: "Plumbing Catalogue",
    price: "",
    image: "/plumbing-32.png",
    description: "UL/FM OS&Y gate valve with flanged ends for fire systems",
  },
  {
    id: 130,
    name: "UL & FM NRS Type Gate Valve Flanged End",
    category: "Plumbing Catalogue",
    price: "",
    image: "/plumbing-33.png",
    description: "UL/FM NRS gate valve with flanged ends for safety systems",
  },
  {
    id: 131,
    name: "Vertical Type Post Indicator Valve",
    category: "Plumbing Catalogue",
    price: "",
    image: "/plumbing-34.png",
    description: "Vertical post indicator valve for fire line supervision",
  },
]
