export interface Product {
  id: number
  name: string
  category: string
  price: string
  image: string
  description: string
}

export const products: Product[] = [
  {
    id: 1,
    name: "Anchor Nut",
    category: "Hardware",
    price: "",
    image: "/anchor-nut.png",
    description: "High quality anchor nuts for secure fastening applications",
  },
  {
    id: 2,
    name: "Tay Rod",
    category: "Construction Materials",
    price: "",
    image: "/tay-rod.png",
    description: "Durable tay rods for construction and reinforcement work",
  },
  {
    id: 3,
    name: "Wing Nut",
    category: "Hardware",
    price: "",
    image: "/wing-nut-img.png",
    description: "Easy-to-use wing nuts for quick assembly and disassembly",
  },
  {
    id: 4,
    name: "M.S Wire",
    category: "Wire Materials",
    price: "",
    image: "/ms-wire-img.png",
    description: "Mild steel wire for various construction applications",
  },
  {
    id: 5,
    name: "Nitrile Coated Safety Gloves",
    category: "Safety Materials",
    price: "",
    image: "/nitrile-coated-safety-gloves-img.png",
    description: "Chemical resistant safety gloves with nitrile coating",
  },
  {
    id: 6,
    name: "MS Construction Wire Nails",
    category: "Nails Materials",
    price: "",
    image: "/ms-construction-wire-nails-img.png",
    description: "Mild steel construction wire nails for heavy-duty applications",
  },
  {
    id: 7,
    name: "Mild Steel Wire Nail",
    category: "Nails Materials",
    price: "",
    image: "/mild-steel-wire-nails-img.png",
    description: "High quality mild steel wire nails for construction work",
  },
  {
    id: 8,
    name: "Sledgehammer Heads",
    category: "Tools",
    price: "",
    image: "/sledgehammer-heads-img.png",
    description: "Heavy duty sledgehammer heads for demolition work",
  },
  {
    id: 9,
    name: "Forged Swivel Clamps (40 mm x 40 mm)",
    category: "Hardware",
    price: "",
    image: "/Forged-swivel-clamp-img.png",
    description: "Forged swivel clamps for secure connections and fittings",
  },
  {
    id: 10,
    name: "Industrial Safety Goggles",
    category: "Safety Materials",
    price: "",
    image: "/industrial-safety-gloves-img.png",
    description: "Protective safety goggles for industrial work environments",
  },
  {
    id: 11,
    name: "Full Body Safety Belt",
    category: "Safety Materials",
    price: "",
    image: "/safety-belt-img.png",
    description: "Complete body safety belt for fall protection and safety",
  },
  {
    id: 12,
    name: "Safety Jacket",
    category: "Safety Materials",
    price: "",
    image: "/safety-jacket-img.png",
    description: "High visibility safety jacket for construction workers",
  },
  {
    id: 13,
    name: "Industrial Safety Shoes",
    category: "Safety Materials",
    price: "",
    image: "/industrial-safety-shoes-img'.png",
    description: "Protective industrial safety shoes for workplace safety",
  },
  {
    id: 14,
    name: "Industrial Dotted Hand Gloves",
    category: "Safety Materials",
    price: "",
    image: "/dotted-gloves-img.png",
    description: "Industrial dotted hand gloves for enhanced grip and protection",
  },
  {
    id: 15,
    name: "PVC Hand Gloves",
    category: "Safety Materials",
    price: "",
    image: "/pvc-gloves-img.png",
    description: "PVC coated hand gloves for chemical and liquid protection",
  },
  {
    id: 16,
    name: "Red Hand Gloves",
    category: "Safety Materials",
    price: "",
    image: "/red-gloves-img.png",
    description: "High visibility red hand gloves for safety and identification",
  },
  {
    id: 17,
    name: "Cotton Hand Gloves",
    category: "Safety Materials",
    price: "",
    image: "/cotton-gloves-img.png",
    description: "Comfortable cotton hand gloves for general work protection",
  },
  {
    id: 18,
    name: "Industries Hand Gloves",
    category: "Safety Materials",
    price: "",
    image: "/industrial-hand-gloves-img.png",
    description: "Professional industrial hand gloves for heavy-duty work",
  },
  {
    id: 19,
    name: "Cement Nails",
    category: "Nails Materials",
    price: "",
    image: "/cement-nails-img.png",
    description: "Specialized cement nails for concrete and masonry work",
  },
  {
    id: 20,
    name: "Concertina Coil Wire",
    category: "Wire Materials",
    price: "",
    image: "/concertina-coil-wire-img.png",
    description: "Security concertina coil wire for perimeter protection",
  },
  {
    id: 21,
    name: "G.I Barbed Wire",
    category: "Wire Materials",
    price: "",
    image: "/GI-barbed-wire-img.png",
    description: "Galvanized iron barbed wire for fencing and security",
  },
  {
    id: 22,
    name: "Barricade Tape",
    category: "Safety Materials",
    price: "",
    image: "/barricade-tape-img.png",
    description: "High visibility barricade tape for safety and warning purposes",
  },
  {
    id: 23,
    name: "M.S Binding Wire ",
    category: "Wire Materials",
    price: "",
    image: "/ms-banding-wire-u-img.png",
    description: "Mild steel banding wire for packaging and bundling applications",
  },
  {
    id: 24,
    name: "Galvanize Iron Wire",
    category: "Wire Materials",
    price: "",
    image: "/galvanize-iron-wire-img.png",
    description: "Galvanized iron wire for corrosion resistance and durability",
  },
  {
    id: 25,
    name: "Galista Safety Shoes",
    category: "Safety Materials",
    price: "",
    image: "/galista-safety-shoes.png",
    description: "Premium Galista safety shoes for industrial protection",
  },
  {
    id: 26,
    name: "Elecant Safety Shoes",
    category: "Safety Materials",
    price: "",
    image: "/elecant-safety-shoes.png",
    description: "Elegant safety shoes combining style with workplace protection",
  },
  {
    id: 27,
    name: "PVC Farming Wire",
    category: "Wire Materials",
    price: "",
    image: "/pvc-farming-wire.png",
    description: "PVC coated farming wire for agricultural applications",
  },
  {
    id: 28,
    name: "PVC Coated Cloth Wire",
    category: "Wire Materials",
    price: "",
    image: "/pvc-coated-cloth-wire-img.png",
    description: "PVC coated cloth wire for electrical and construction applications",
  },
  {
    id: 29,
    name: "Nails",
    category: "Nails Materials",
    price: "",
    image: "/nails-img.png",
    description: "High quality construction nails for various building applications",
  },
  {
    id: 30,
    name: "Quarter Pin",
    category: "Hardware",
    price: "",
    image: "/quarter-pin-img.png",
    description: "Precision quarter pins for mechanical and construction applications",
  },
  {
    id: 31,
    name: "L.J. Pipe Hook",
    category: "Hardware",
    price: "",
    image: "/L-J-pipe-hook-img.png",
    description: "L.J. pipe hooks for secure pipe mounting and support systems",
  },
  {
    id: 32,
    name: "PVC Cap",
    category: "Hardware",
    price: "",
    image: "/pvc-cap-img.png",
    description: "PVC caps for pipe protection and sealing applications",
  },
  {
    id: 33,
    name: "Nut",
    category: "Hardware",
    price: "",
    image: "/nut-img.png",
    description: "Standard nuts for fastening and assembly applications",
  },
  {
    id: 34,
    name: "Ribit",
    category: "Hardware",
    price: "",
    image: "/ribit-img.png",
    description: "Ribit fasteners for secure connections and structural applications",
  },
  {
    id: 35,
    name: "L Hook",
    category: "Hardware",
    price: "",
    image: "/L-hook-img.png",
    description: "L-shaped hooks for hanging and mounting applications",
  },
  {
    id: 36,
    name: "C Hook",
    category: "Hardware",
    price: "",
    image: "/C-hook-img.png",
    description: "C-shaped hooks for versatile hanging and support systems",
  },
  {
    id: 37,
    name: "Patti Hook",
    category: "Hardware",
    price: "",
    image: "/patti-hook-img.png",
    description: "Patti hooks for specialized mounting and hanging applications",
  },
  {
    id: 38,
    name: "Pipe Hook",
    category: "Hardware",
    price: "",
    image: "/pipe-hook-img.png",
    description: "Pipe hooks designed for secure pipe mounting and support",
  },
  {
    id: 39,
    name: "Cycle Hook",
    category: "Hardware",
    price: "",
    image: "/cycle-hook-img.png",
    description: "Cycle hooks for bicycle storage and mounting solutions",
  },
  {
    id: 40,
    name: "S Hook",
    category: "Hardware",
    price: "",
    image: "/S-hook-img.png",
    description: "S-shaped hooks for versatile hanging and connection applications",
  },
  {
    id: 41,
    name: "Box Hook",
    category: "Hardware",
    price: "",
    image: "/box-hook-img.png",
    description: "Box hooks for secure box and container mounting",
  },
  {
    id: 42,
    name: "Gadar Hook",
    category: "Hardware",
    price: "",
    image: "/gadar-hook-img.png",
    description: "Gadar hooks for heavy-duty mounting and support applications",
  },
  {
    id: 43,
    name: "Dag",
    category: "Hardware",
    price: "",
    image: "/dag-img.png",
    description: "Dag fasteners for secure connections and structural applications",
  },
  {
    id: 44,
    name: "Hole Pass",
    category: "Hardware",
    price: "",
    image: "/hole-paas-img.png",
    description: "Hole pass components for cable and wire management systems",
  },
  {
    id: 45,
    name: "Colom Patti",
    category: "Hardware",
    price: "",
    image: "/colom-patti-img.png",
    description: "Colom patti for structural support and reinforcement applications",
  },
  {
    id: 46,
    name: "Pully",
    category: "Hardware",
    price: "",
    image: "/pully-img.png",
    description: "Standard pulleys for lifting and mechanical applications",
  },
  {
    id: 47,
    name: "Wheel Pully",
    category: "Hardware",
    price: "",
    image: "/wheel-pully-img.png",
    description: "Wheel pulleys for enhanced mechanical advantage and lifting",
  },
  {
    id: 48,
    name: "Buckle",
    category: "Hardware",
    price: "",
    image: "/buckle-img.png",
    description: "Buckles for fastening and securing applications",
  },
  {
    id: 49,
    name: "China Double Pully",
    category: "Hardware",
    price: "",
    image: "/china-double-pully-img.png",
    description: "China double pulleys for heavy-duty lifting and mechanical systems",
  },
  {
    id: 50,
    name: "Brass Pully",
    category: "Hardware",
    price: "",
    image: "/brass-pully-img.png",
    description: "Brass pulleys for corrosion-resistant mechanical applications",
  },
  {
    id: 51,
    name: "Brass Double Pully",
    category: "Hardware",
    price: "",
    image: "/brass-double-pully-img.png",
    description: "Brass double pulleys for heavy-duty corrosion-resistant applications",
  },
  {
    id: 52,
    name: "Small Nut",
    category: "Hardware",
    price: "",
    image: "/small-nut-img.png",
    description: "Small nuts for precision fastening and assembly applications",
  },
]
